### ISSUE TITLE
filepath not found on first sardine import

### ISSUE THREAD

**Issue by Pipazoul** [Bubobubobubobubo/Sardine#26]
After a succesfull install (`pip3 install -e .`)
when using for the first time `from sardine import *` i've got the following error

```bash
File "/sardine/io/UserConfig.py", line 84, in read_user_configuration
create_template_configuration_file(config_file)
TypeError: create_template_configuration_file() missing 1 required positional argument: 'file_path'
```

The error disapeared on the second import attempt

**Comment by thegamecracks** [comment]
This bug appears to have been introduced in commit 8dd375c (dev branch), after a change to the function signature was not reflected in the call to it on the first run:

```diff
diff --git a/sardine/io/UserConfig.py b/sardine/io/UserConfig.py
index f609dad..0f720ff 100644
- def create_template_configuration_file(file_path: str) -> None:
+ def create_template_configuration_file(user_dir: Path, file_path: Path) -> None:
```

https://github.com/Bubobubobubobubo/Sardine/blob/8dd375c8f3ca482cdb1302ffb3d9a5f50d3f0feb/sardine/io/UserConfig.py#L84

This was likely fixed (by accident) after commit 69cab98, and I cannot reproduce the issue as of cbca0f6.
